#!/usr/bin/env python
import sys
sys.path.append('/home/zonion/speedio')
import rest,os

def unicode_2_str(o):
    if isinstance(o, dict):
        for k, v in o.items():
#            import pdb
#            pdb.set_trace()
            del o[k]
            o[str(k)] = v
            if isinstance(v, unicode):
                o[k] = str(v)
            elif isinstance(v, bool):
                o[k] = str(v).lower()
            elif isinstance(v, dict):
                o[k] = unicode_2_str(v)
    return o

def test():
    r = rest.rest()
    o = r.devicestatus.query()
    disks = r.disk.list()
    raids = r.raid.list()
    device =  dict(disks=disks,raids=raids)
    print device

if __name__ == '__main__':
    r = rest.rest()
    o = r.devicestatus.query()
    disks_u = r.disk.list()
    raids_u = r.raid.list()
    
    disk,raid = [],[]
    for i in disks_u:
        disk.append(unicode_2_str(i))
    for i in raids_u:
        raid.append(unicode_2_str(i))

    
    device=dict(disks=disk,raids=raid)
    print device
    #test()
